import { money, iso, parse, events, forecast, detectRecurring } from './finance.js';
import { seed } from './data.js';
const key='onepay-demo-v1';
let state; try {state=JSON.parse(localStorage.getItem(key));if(state?.version!==1)state=seed();}catch{state=seed();}
let page='Overview', filter='All', query='', month=new Date(); month.setDate(1);
const today=iso(new Date());
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=date=>parse(date).toLocaleDateString('en-AU',{day:'numeric',month:'short'});
const icon={Overview:'◫',Calendar:'▦',Payments:'⇄',Insights:'✧',Accounts:'▤',Settings:'⚙'};
function save(action) {state.audit.unshift({action,date:new Date().toISOString()});state.audit=state.audit.slice(0,100);try{localStorage.setItem(key,JSON.stringify(state));}catch{toast('Browser storage is unavailable. Changes last for this session.');}render();}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4000);}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'Disconnected account';}
function rows(items){return items.length?items.map(p=>`<button class="payment-row" data-edit="${esc(p.id)}"><span class="merchant-icon ${p.kind==='income'?'green':''}">${esc(p.merchant.slice(0,1))}</span><span class="merchant"><strong>${esc(p.merchant)}</strong><small>${esc(p.category)} · ${esc(p.frequency)}</small></span><span class="row-date">${pretty(p.date||p.nextDate)}<small>${esc(accountName(p.accountId))}</small></span><span class="amount ${p.kind==='income'?'positive':''}">${p.kind==='income'?'+':''}${money(Math.abs(p.amount))}<small>${p.status==='active'?'Expected':'Tracking paused'}</small></span><span class="chevron">↗</span></button>`).join(''):'<div class="empty">Nothing here yet. Add a commitment to get started.</div>';}
function chart(f){const values=f.points.map(p=>p.balance);const low=Math.min(0,...values),high=Math.max(1,...values);const coords=values.map((v,i)=>`${20+i/(values.length-1)*760},${170-(v-low)/(high-low)*140}`).join(' ');return `<div class="chart"><svg viewBox="0 0 800 200" role="img" aria-label="Forecast ranges from ${money(f.minimum)} to ${money(Math.max(...values))}, ending at ${money(f.final)}"><path d="M20 50H780 M20 110H780 M20 170H780" class="grid-line"/><polygon points="20,190 ${coords} 780,190" class="chart-fill"/><polyline points="${coords}" class="chart-line"/></svg><div class="chart-labels"><span>Today</span><span>Day 7</span><span>Day 14</span><span>Day 21</span><span>Day 30</span></div></div>`;}
function overview(){const f=forecast(state,today);const upcoming=events(state,today,7);const next=events(state,today,60).find(e=>e.kind==='income');return `<div class="greeting"><div><span class="eyebrow">YOUR MONEY, IN VIEW</span><h1>A little clarity. A lot more calm.</h1><p>Here's what your money is doing, ${esc(state.profile.name)}.</p></div><button class="primary" data-action="add">+ Add payment</button></div><div class="stats"><section class="safe-card"><div class="stat-label">Estimated safe to spend <span>↗</span></div><strong>${money(f.safe)}</strong><p>Lowest 30-day balance, less your ${money(state.buffer)} buffer.</p><span class="pill light">Savings kept aside</span></section><section class="stat-card"><span class="stat-label">Available balance</span><strong>${money(f.balance)}</strong><p>Across connected spending & bills accounts</p></section><section class="stat-card"><span class="stat-label">Committed · next 30 days</span><strong>${money(f.committed)}</strong><p>${events(state,today).filter(e=>e.amount<0).length} expected payments</p></section><section class="stat-card"><span class="stat-label">Next payday</span><strong>${next?pretty(next.date):'Not set'}</strong><p>${next?`${money(next.amount)} expected`:'Add your income to plan ahead'}</p></section></div><div class="main-grid"><section class="panel"><div class="panel-heading"><div><h2>Your next 30 days</h2><p>Expected income and commitments, together.</p></div><span class="pill">Cash-flow forecast</span></div>${chart(f)}<div class="forecast-summary"><div><small>Expected income</small><strong class="positive">+${money(f.incoming)}</strong></div><div><small>Lowest projected balance</small><strong class="${f.minimum<0?'negative':''}">${money(f.minimum)}</strong></div><div><small>In 30 days</small><strong>${money(f.final)}</strong></div></div></section><section class="insight-card"><span class="eyebrow">A HEADS-UP</span><div class="insight-symbol">✧</div><h2>${f.minimum<state.buffer?'A little room to plan ahead':'Your month is taking shape'}</h2><p>${f.minimum<state.buffer?`Your lowest forecast balance is ${money(f.minimum)}. Review upcoming commitments before making new plans.`:'Keep your recurring commitments in view and review the payments we’ve detected.'}</p><button data-page="Insights">Explore insights <span>→</span></button></section></div><section class="panel"><div class="panel-heading"><div><h2>Coming up this week <span class="count">${upcoming.length}</span></h2><p>The small things and the big things, all in one place.</p></div><button class="text-button" data-page="Calendar">View calendar →</button></div>${rows(upcoming)}</section><p class="footnote">Estimates use tracked income and commitments. Everyday spending and untracked bills are not included.</p>`;}
function payments(){const list=[...state.payments,...state.income].filter(p=>(filter==='All'||(filter==='Income'?p.kind==='income':filter==='Paused'?p.status==='paused':p.category===filter))&&p.merchant.toLowerCase().includes(query.toLowerCase()));return `<div class="greeting"><div><span class="eyebrow">EVERY COMMITMENT, ONE PLACE</span><h1>Payments & income</h1><p>Track what’s coming in and what’s going out.</p></div><button class="primary" data-action="add">+ Add commitment</button></div><div class="toolbar"><div class="tabs">${['All','Subscription','Utilities','Income','Paused'].map(v=>`<button data-filter="${v}" class="${filter===v?'selected':''}">${v}</button>`).join('')}</div><input id="search" aria-label="Search commitments" placeholder="Search commitments…" value="${esc(query)}"></div><section class="panel">${rows(list)}</section><p class="footnote">Pausing tracking only removes a commitment from forecasts. Contact your bank or merchant to change an actual payment.</p>`;}
function calendar(){const start=iso(month), last=new Date(month.getFullYear(),month.getMonth()+1,0);const scheduled=events(state,start,last.getDate()-1);const offset=(month.getDay()+6)%7;return `<div class="greeting"><div><span class="eyebrow">THE CALENDAR FOR YOUR MONEY</span><h1>Financial calendar</h1><p>Make room for what’s next.</p></div><button class="primary" data-action="add">+ Add commitment</button></div><section class="panel"><div class="panel-heading"><h2>${month.toLocaleDateString('en-AU',{month:'long',year:'numeric'})}</h2><div class="tabs"><button data-action="prev" aria-label="Previous month">←</button><button data-action="month-today">Today</button><button data-action="next" aria-label="Next month">→</button></div></div><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="weekday">${d}</div>`).join('')}${'<div class="day blank"></div>'.repeat(offset)}${Array.from({length:last.getDate()},(_,i)=>{const d=`${start.slice(0,8)}${String(i+1).padStart(2,'0')}`;return `<div class="day ${d===today?'today':''}"><span class="day-number">${i+1}</span>${scheduled.filter(e=>e.date===d).map(e=>`<button class="event ${e.kind==='income'?'income':''}" data-edit="${esc(e.id)}"><strong>${esc(e.merchant)}</strong><span>${e.kind==='income'?'+':''}${money(Math.abs(e.amount))}</span></button>`).join('')}</div>`;}).join('')}</div></section><p class="footnote">Green events are expected income. All dates are estimates or your manually entered dates.</p>`;}
function insights(){const detections=detectRecurring(state.transactions).filter(d=>![...state.payments,...state.income].some(p=>p.merchant.toLowerCase()===d.merchant.toLowerCase()&&p.accountId===d.accountId));const subs=state.payments.filter(p=>p.category==='Subscription'&&p.status==='active');const factors={weekly:52/12,fortnightly:26/12,monthly:1,quarterly:1/3,annually:1/12};const monthly=Math.round(subs.reduce((s,p)=>s+p.amount*factors[p.frequency],0));return `<div class="greeting"><div><span class="eyebrow">UNDERSTAND YOUR RECURRING LIFE</span><h1>Small insights. Better decisions.</h1><p>Patterns from your sample transaction history.</p></div></div><div class="stats two"><section class="safe-card"><span class="stat-label">Subscriptions · monthly equivalent</span><strong>${money(monthly)}</strong><p>${money(monthly*12)} per year across ${subs.length} tracked services.</p></section><section class="stat-card"><span class="stat-label">New recurring patterns</span><strong>${detections.length}</strong><p>Review before adding these to your forecast.</p></section></div><section class="panel"><div class="panel-heading"><div><h2>Detected for your review</h2><p>Three or more transactions with a regular cadence.</p></div></div>${detections.length?detections.map(d=>`<div class="detection"><span class="merchant-icon">${esc(d.merchant[0])}</span><div><h3>${esc(d.merchant)}</h3><p>${money(d.amount)} · ${d.frequency} · ${d.confidence}% pattern confidence</p>${d.amount>d.previousAmount?`<p class="negative">Latest amount increased by ${money(d.amount-d.previousAmount)}.</p>`:''}</div><button class="primary" data-track="${esc(d.id)}">Track payment</button></div>`).join(''):'<div class="empty">All detected recurring payments have been reviewed.</div>'}</section><section class="panel"><div class="panel-heading"><h2>Tracked subscriptions</h2></div>${rows(subs)}</section>`;}
function accounts(){return `<div class="greeting"><div><span class="eyebrow">YOUR ACCOUNTS, TOGETHER</span><h1>Connected accounts</h1><p>Manage sample accounts and their data permissions.</p></div><button class="primary" data-action="connect">+ Connect sandbox bank</button></div><div class="account-grid">${state.accounts.map(a=>`<section class="panel account"><div class="panel-heading"><span class="bank-logo">${esc(a.bank)}</span><span class="pill">${a.connected?'Sandbox connected':'Disconnected'}</span></div><h2>${esc(a.name)}</h2><p>•••• ${esc(a.mask)} · ${esc(a.role)}</p><strong class="account-balance">${money(a.balance)}</strong><p>${a.role==='savings'?'Excluded from spending forecasts':'Included in forecasts while connected'}</p><hr><small>Sample permissions: account details, balances, transactions.</small><button class="secondary" data-consent="${esc(a.id)}">${a.connected?'Manage consent':'Reconnect sandbox account'}</button></section>`).join('')}</div><p class="footnote">This is a simulated connection. OnePay does not request banking credentials or access real accounts.</p>`;}
function settings(){return `<div class="greeting"><div><span class="eyebrow">MAKE IT YOURS</span><h1>Preferences & data</h1><p>Your local demo, under your control.</p></div></div><section class="panel settings"><form id="settings-form"><label>Display name<input name="name" required maxlength="50" value="${esc(state.profile.name)}"></label><label>Safety buffer (AUD)<input name="buffer" type="number" min="0" max="1000000" step="0.01" required value="${state.buffer/100}"></label><label class="check"><input name="reminders" type="checkbox" ${state.reminders?'checked':''}> Show upcoming-payment reminders in this app</label><p class="footnote">Browser push, email and SMS delivery are not connected.</p><button class="primary">Save preferences</button></form><hr><h2>Your demo data</h2><p>Stored in this browser. Export your changes or restore the sample scenario.</p><div class="actions"><button class="secondary" data-action="export">Export JSON</button><button class="secondary" data-action="reset">Reset demo data</button></div></section><section class="panel"><div class="panel-heading"><h2>Local activity</h2><span class="pill">Demo log</span></div>${state.audit.slice(0,10).map(a=>`<div class="audit"><span>${esc(a.action)}</span><small>${new Date(a.date).toLocaleString('en-AU')}</small></div>`).join('')||'<div class="empty">Your changes will appear here.</div>'}</section>`;}
function render(){document.querySelector('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#" data-page="Overview"><span class="brand-mark">↗</span>onepay<span class="brand-dot">.</span></a><div class="nav-caption">YOUR FINANCIAL SPACE</div><nav>${Object.keys(icon).map(p=>`<button data-page="${p}" class="nav-item ${page===p?'active':''}"><span>${icon[p]}</span>${p}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="sandbox-dot"></div><strong>Room to explore</strong><p>Sample data. Real possibilities.</p><span class="pill">Sandbox workspace</span></div><div class="profile"><span class="avatar">${esc(state.profile.name[0]||'A')}</span><div><strong>${esc(state.profile.name)}</strong><small>Personal workspace</small></div></div></aside><main><header><div class="breadcrumb">My workspace <span>/</span> <strong>${page}</strong></div><div class="header-right"><span class="demo-label">DEMO MODE</span><button class="notification" data-action="alerts" aria-label="View upcoming payment reminders">♧<span class="notification-dot"></span></button><span class="avatar small">${esc(state.profile.name[0]||'A')}</span></div></header><div class="content">${({Overview:overview,Payments:payments,Calendar:calendar,Insights:insights,Accounts:accounts,Settings:settings}[page])()}<footer>onepay · Understand. Plan. Breathe.<span>AUD · Local demo · No money movement</span></footer></div></main>`;}
const modal=document.querySelector('#modal');
function openModal(body){modal.innerHTML=`<div class="modal-header"><span class="eyebrow">ONEPAY WORKSPACE</span><button class="close" data-action="close" aria-label="Close dialog">×</button></div>${body}`;modal.showModal();}
function edit(id){const item=[...state.payments,...state.income].find(p=>p.id===id);openModal(`<h2>${item?'Edit commitment':'A new commitment'}</h2><p>Keep your forecast up to date.</p><form id="payment-form" data-id="${esc(id||'')}"><label>Merchant or income source<input name="merchant" required maxlength="80" value="${esc(item?.merchant||'')}"></label><div class="form-grid"><label>Amount (AUD)<input name="amount" type="number" min="0.01" max="1000000" step="0.01" required value="${item?item.amount/100:''}"></label><label>Type<select name="kind">${['expense','income'].map(v=>`<option ${item?.kind===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Frequency<select name="frequency">${['weekly','fortnightly','monthly','quarterly','annually'].map(v=>`<option ${item?.frequency===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Next expected date<input name="nextDate" type="date" required value="${item?.nextDate||today}"></label></div><label>Account<select name="accountId">${state.accounts.map(a=>`<option value="${esc(a.id)}" ${item?.accountId===a.id?'selected':''}>${esc(a.name)}${a.connected?'':' (disconnected)'}</option>`).join('')}</select></label><label>Category<select name="category">${['Subscription','Housing','Utilities','Insurance','Health','Loan','Salary','Other'].map(v=>`<option ${item?.category===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Notes<textarea name="notes" maxlength="500">${esc(item?.notes||'')}</textarea></label><label class="check"><input name="paused" type="checkbox" ${item?.status==='paused'?'checked':''}> Pause tracking in OnePay</label><p class="footnote">Changes affect your plan only. Your bank and merchant agreements stay unchanged.</p><div class="actions"><button class="primary">Save commitment</button>${item?`<button type="button" class="danger" data-delete="${esc(item.id)}">Remove tracking</button>`:''}</div></form>`);}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
 if(b.dataset.page){e.preventDefault();page=b.dataset.page;query='';filter='All';render();return;}
 if(b.dataset.filter){filter=b.dataset.filter;render();return;}
 if(b.dataset.edit){edit(b.dataset.edit);return;}
 if(b.dataset.delete){state.payments=state.payments.filter(p=>p.id!==b.dataset.delete);state.income=state.income.filter(p=>p.id!==b.dataset.delete);modal.close();save('Commitment tracking removed');return;}
 if(b.dataset.track){const d=detectRecurring(state.transactions).find(d=>d.id===b.dataset.track);if(d){(d.kind==='income'?state.income:state.payments).push(d);save(`Tracking added: ${d.merchant}`);toast('Added to your payments and forecast.');}return;}
 if(b.dataset.consent){const a=state.accounts.find(a=>a.id===b.dataset.consent);openModal(`<h2>${esc(a.bank)} · ${esc(a.name)}</h2><p>This sandbox simulates permissions for account details, balances and transaction history. No real bank data is shared.</p><p>Disconnecting excludes this account and its commitments from forecasts. Existing sample records remain until you reset the demo.</p><button class="primary" data-toggle-account="${esc(a.id)}">${a.connected?'Revoke sandbox consent':'Grant sandbox consent'}</button>`);return;}
 if(b.dataset.toggleAccount){const a=state.accounts.find(a=>a.id===b.dataset.toggleAccount);a.connected=!a.connected;modal.close();save(a.connected?'Sandbox consent granted':'Sandbox consent revoked');return;}
 const action=b.dataset.action;
 if(action==='close')modal.close();
 if(action==='add')edit();
 if(action==='prev'||action==='next'){month.setMonth(month.getMonth()+(action==='next'?1:-1));render();}
 if(action==='month-today'){month=new Date();month.setDate(1);render();}
 if(action==='connect')openModal('<h2>Connect a sandbox bank</h2><p>Try a simulated bank connection with sample data. No banking login is required.</p><form id="connect-form"><label>Institution<select name="bank"><option>ANZ</option><option>NAB</option><option>Westpac</option><option>Commonwealth Bank</option></select></label><label class="check"><input type="checkbox" required> I agree to simulate sharing account details, balances and transaction history.</label><button class="primary">Connect sample account</button></form>');
 if(action==='alerts'){const due=state.reminders?events(state,today,3).filter(e=>e.kind!=='income'):[];openModal(`<h2>Upcoming reminders</h2>${!state.reminders?'<p>Reminders are turned off in Preferences.</p>':due.length?due.map(p=>`<div class="audit"><strong>${esc(p.merchant)}</strong><span>${money(Math.abs(p.amount))} · ${pretty(p.date)}</span></div>`).join(''):'<p>No payments expected in the next three days.</p>'}`);}
 if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='onepay-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(action==='reset')openModal('<h2>Restore the sample scenario?</h2><p>This deletes the commitments, preferences and account changes you made in this browser.</p><button class="danger" data-action="confirm-reset">Reset demo data</button>');
 if(action==='confirm-reset'){state=seed();modal.close();save('Demo reset');}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;const position=e.target.selectionStart;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(position,position);}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,data=new FormData(form);
 if(form.id==='payment-form'){const amount=Math.round(Number(data.get('amount'))*100);const merchant=String(data.get('merchant')).trim();if(!merchant||!Number.isSafeInteger(amount)||amount<=0)return;const id=form.dataset.id||crypto.randomUUID();const item={id,merchant,amount,kind:data.get('kind'),frequency:data.get('frequency'),nextDate:data.get('nextDate'),accountId:data.get('accountId'),category:data.get('kind')==='income'?'Salary':data.get('category'),notes:data.get('notes'),status:data.has('paused')?'paused':'active',confidence:100};state.payments=state.payments.filter(p=>p.id!==id);state.income=state.income.filter(p=>p.id!==id);(item.kind==='income'?state.income:state.payments).push(item);modal.close();save(`Commitment saved: ${merchant}`);toast('Your calendar and forecast are updated.');}
 if(form.id==='settings-form'){state.profile.name=String(data.get('name')).trim()||'Alex';state.buffer=Math.round(Number(data.get('buffer'))*100);state.reminders=data.has('reminders');save('Preferences updated');toast('Preferences saved.');}
 if(form.id==='connect-form'){state.accounts.push({id:crypto.randomUUID(),bank:data.get('bank'),name:'Sandbox everyday',mask:'0001',balance:150000,role:'spending',connected:true});modal.close();save('Sandbox bank connected with simulated consent');toast('Sample account connected.');}
});
render();
